#!/bin/sh
# Renders public/og.png, the one social card every page's og:image points at.
# The PNG is committed, so a build needs neither rsvg-convert nor ImageMagick;
# run this after changing the banner, the headline, or the palette.
#
# The card has to survive Slack shrinking it to a thumbnail a couple of hundred
# pixels wide, which is what decides the sizes here. The negative
# interline-spacing is leading tighter than the face's own, which two lines of
# display type want, and 104pt leaves the longer line 40px short of the right
# margin, where 110pt overruns it.
set -eu

cd "$(dirname "$0")/.."

# Always the dark banner: og:image has no media query.
banner=public/grove-banner-dark.svg
# ImageMagick reads woff2 through freetype, so the card is set in the site's own
# faces rather than whatever the machine happens to have.
serif=node_modules/@fontsource/source-serif-4/files/source-serif-4-latin-700-normal.woff2
sans=node_modules/@fontsource/inter/files/inter-latin-400-normal.woff2
mono=node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2
out=public/og.png
# The one place the card's size is written; stamped below so the layouts
# declare the size the image really is.
width=1200
height=630

# ImageMagick 7 is one `magick` binary; 6 draws with `convert`.
if command -v magick >/dev/null 2>&1; then
  draw=magick
else
  draw=convert
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

rsvg-convert -w 240 "$banner" -o "$work/banner.png"

# The card is static, so the two handles under the rule are not read from the
# config: a repo rename or a domain change lands here too.
"$draw" -size "${width}x${height}" "xc:#14170F" \
  "$work/banner.png" -geometry +88+72 -composite \
  -font "$serif" -pointsize 104 -fill "#F0ECE3" -interline-spacing -18 \
  -gravity northwest -annotate +88+192 "All your worktrees,
running at once" \
  -font "$sans" -pointsize 36 -fill "#7FC96B" \
  -annotate +88+448 "Each with its own hostname, ports, and env vars." \
  -fill "#2F3A2A" -draw "rectangle 88,524 1112,525" \
  -font "$mono" -pointsize 25 -fill "#8FA394" -annotate +88+550 "grove-sh/cli" \
  -gravity northeast -annotate +88+550 "grov.site" \
  -strip -depth 8 "$out"

# Stamped here rather than hashed at build: the build bundles its modules before
# running them, so a path to the PNG resolves into the bundle. sha256sum is GNU
# coreutils; macOS spells it shasum.
digest=$( { sha256sum "$out" 2>/dev/null || shasum -a 256 "$out"; } | cut -c1-8)
cat > components/og-version.ts <<VERSION
// Generated by scripts/og-card.sh. Regenerate the card rather than editing it.
export const ogVersion = "$digest";
export const ogWidth = $width;
export const ogHeight = $height;
VERSION
